# -*- coding: utf-8 -*-
from __future__ import unicode_literals

import jsonfield.fields
from django.db import models, migrations


class Migration(migrations.Migration):
    dependencies = [
        ('resorts', '0019_resort_default_unit_paper'),
    ]

    operations = [
        migrations.AddField(
            model_name='resort',
            name='dispatch_field_choice',
            field=jsonfield.fields.JSONField(
                default=[{b'field_key': b'name', b'field_position': 1}, {b'field_key': b'phone', b'field_position': 2},
                         {b'field_key': b'body_part', b'field_position': 3},
                         {b'field_key': b'field_52d48077a16be', b'field_position': 4}],
                verbose_name=b'choice for dispatch screen'),
        ),
        migrations.AlterField(
            model_name='resort',
            name='timezone',
            field=models.CharField(blank=True, max_length=50, choices=[(b'Atlantic/Madeira', b'Atlantic/Madeira'),
                                                                       (b'America/Cancun', b'America/Cancun'),
                                                                       (b'America/Iqaluit', b'America/Iqaluit'),
                                                                       (b'America/Menominee', b'America/Menominee'),
                                                                       (b'Asia/Gaza', b'Asia/Gaza'),
                                                                       (b'America/Pangnirtung', b'America/Pangnirtung'),
                                                                       (b'Asia/Tehran', b'Asia/Tehran'),
                                                                       (b'America/Vancouver', b'America/Vancouver'),
                                                                       (b'America/Miquelon', b'America/Miquelon'),
                                                                       (b'Asia/Nicosia', b'Asia/Nicosia'),
                                                                       (b'Asia/Amman', b'Asia/Amman'),
                                                                       (b'Antarctica/Davis', b'Antarctica/Davis'),
                                                                       (b'America/Guyana', b'America/Guyana'),
                                                                       (b'Africa/Ndjamena', b'Africa/Ndjamena'),
                                                                       (b'Australia/Adelaide', b'Australia/Adelaide'),
                                                                       (b'Africa/Dakar', b'Africa/Dakar'),
                                                                       (b'America/Tijuana', b'America/Tijuana'),
                                                                       (b'Africa/Lusaka', b'Africa/Lusaka'),
                                                                       (b'Africa/Ceuta', b'Africa/Ceuta'),
                                                                       (b'Asia/Choibalsan', b'Asia/Choibalsan'),
                                                                       (b'Asia/Tokyo', b'Asia/Tokyo'),
                                                                       (b'Asia/Colombo', b'Asia/Colombo'), (
                                                                       b'America/Rankin_Inlet',
                                                                       b'America/Rankin_Inlet'),
                                                                       (b'Africa/Harare', b'Africa/Harare'),
                                                                       (b'America/Guatemala', b'America/Guatemala'),
                                                                       (b'Asia/Bahrain', b'Asia/Bahrain'), (
                                                                       b'America/Indiana/Petersburg',
                                                                       b'America/Indiana/Petersburg'),
                                                                       (b'Pacific/Palau', b'Pacific/Palau'),
                                                                       (b'Africa/Kampala', b'Africa/Kampala'),
                                                                       (b'America/Caracas', b'America/Caracas'),
                                                                       (b'Africa/Algiers', b'Africa/Algiers'),
                                                                       (b'Asia/Qatar', b'Asia/Qatar'),
                                                                       (b'Europe/Zurich', b'Europe/Zurich'),
                                                                       (b'America/Chihuahua', b'America/Chihuahua'), (
                                                                       b'America/Argentina/Catamarca',
                                                                       b'America/Argentina/Catamarca'),
                                                                       (b'America/Jamaica', b'America/Jamaica'),
                                                                       (b'America/Asuncion', b'America/Asuncion'), (
                                                                       b'America/Santa_Isabel',
                                                                       b'America/Santa_Isabel'),
                                                                       (b'America/Godthab', b'America/Godthab'),
                                                                       (b'America/Guayaquil', b'America/Guayaquil'),
                                                                       (b'Asia/Khandyga', b'Asia/Khandyga'),
                                                                       (b'Africa/Johannesburg', b'Africa/Johannesburg'),
                                                                       (b'America/Bahia', b'America/Bahia'),
                                                                       (b'America/St_Kitts', b'America/St_Kitts'),
                                                                       (b'America/Anguilla', b'America/Anguilla'),
                                                                       (b'America/Montserrat', b'America/Montserrat'),
                                                                       (b'America/Goose_Bay', b'America/Goose_Bay'),
                                                                       (b'Africa/Asmara', b'Africa/Asmara'), (
                                                                       b'America/Dawson_Creek',
                                                                       b'America/Dawson_Creek'),
                                                                       (b'Pacific/Norfolk', b'Pacific/Norfolk'),
                                                                       (b'Europe/Minsk', b'Europe/Minsk'),
                                                                       (b'Atlantic/St_Helena', b'Atlantic/St_Helena'), (
                                                                       b'America/Indiana/Indianapolis',
                                                                       b'America/Indiana/Indianapolis'),
                                                                       (b'Asia/Jayapura', b'Asia/Jayapura'),
                                                                       (b'Europe/Chisinau', b'Europe/Chisinau'), (
                                                                       b'America/Indiana/Valparaiso',
                                                                       b'America/Indiana/Valparaiso'),
                                                                       (b'Indian/Antananarivo', b'Indian/Antananarivo'),
                                                                       (b'America/New_York', b'America/New_York'),
                                                                       (b'Europe/Samara', b'Europe/Samara'),
                                                                       (b'Asia/Rangoon', b'Asia/Rangoon'),
                                                                       (b'Pacific/Guadalcanal', b'Pacific/Guadalcanal'),
                                                                       (b'Atlantic/Cape_Verde', b'Atlantic/Cape_Verde'),
                                                                       (b'Asia/Almaty', b'Asia/Almaty'),
                                                                       (b'Africa/Cairo', b'Africa/Cairo'), (
                                                                       b'America/Kentucky/Louisville',
                                                                       b'America/Kentucky/Louisville'),
                                                                       (b'Asia/Yekaterinburg', b'Asia/Yekaterinburg'), (
                                                                       b'America/North_Dakota/New_Salem',
                                                                       b'America/North_Dakota/New_Salem'),
                                                                       (b'America/Paramaribo', b'America/Paramaribo'),
                                                                       (b'Africa/Libreville', b'Africa/Libreville'),
                                                                       (b'America/Sitka', b'America/Sitka'),
                                                                       (b'Indian/Reunion', b'Indian/Reunion'),
                                                                       (b'Pacific/Noumea', b'Pacific/Noumea'),
                                                                       (b'America/Martinique', b'America/Martinique'),
                                                                       (b'Asia/Ust-Nera', b'Asia/Ust-Nera'),
                                                                       (b'America/La_Paz', b'America/La_Paz'),
                                                                       (b'Asia/Qyzylorda', b'Asia/Qyzylorda'),
                                                                       (b'Europe/Volgograd', b'Europe/Volgograd'), (
                                                                       b'America/Argentina/San_Juan',
                                                                       b'America/Argentina/San_Juan'), (
                                                                       b'America/Indiana/Vincennes',
                                                                       b'America/Indiana/Vincennes'),
                                                                       (b'Atlantic/Azores', b'Atlantic/Azores'),
                                                                       (b'America/Anchorage', b'America/Anchorage'),
                                                                       (b'Europe/Belgrade', b'Europe/Belgrade'),
                                                                       (b'Asia/Aden', b'Asia/Aden'),
                                                                       (b'Europe/Bucharest', b'Europe/Bucharest'),
                                                                       (b'Pacific/Wake', b'Pacific/Wake'),
                                                                       (b'America/Tortola', b'America/Tortola'),
                                                                       (b'Australia/Hobart', b'Australia/Hobart'),
                                                                       (b'America/Cayenne', b'America/Cayenne'),
                                                                       (b'Pacific/Tongatapu', b'Pacific/Tongatapu'),
                                                                       (b'America/Regina', b'America/Regina'),
                                                                       (b'America/Barbados', b'America/Barbados'),
                                                                       (b'America/Atikokan', b'America/Atikokan'),
                                                                       (b'Europe/Helsinki', b'Europe/Helsinki'),
                                                                       (b'America/Monterrey', b'America/Monterrey'),
                                                                       (b'America/Chicago', b'America/Chicago'),
                                                                       (b'Europe/Lisbon', b'Europe/Lisbon'),
                                                                       (b'America/Fortaleza', b'America/Fortaleza'),
                                                                       (b'Europe/Simferopol', b'Europe/Simferopol'),
                                                                       (b'America/Dominica', b'America/Dominica'),
                                                                       (b'America/Grenada', b'America/Grenada'),
                                                                       (b'Asia/Sakhalin', b'Asia/Sakhalin'),
                                                                       (b'Europe/Istanbul', b'Europe/Istanbul'),
                                                                       (b'Europe/Kaliningrad', b'Europe/Kaliningrad'),
                                                                       (b'Africa/Malabo', b'Africa/Malabo'), (
                                                                       b'America/Indiana/Knox',
                                                                       b'America/Indiana/Knox'),
                                                                       (b'Asia/Dushanbe', b'Asia/Dushanbe'),
                                                                       (b'America/St_Thomas', b'America/St_Thomas'),
                                                                       (b'America/Tegucigalpa', b'America/Tegucigalpa'),
                                                                       (b'Indian/Comoro', b'Indian/Comoro'), (
                                                                       b'America/Santo_Domingo',
                                                                       b'America/Santo_Domingo'),
                                                                       (b'America/Nassau', b'America/Nassau'),
                                                                       (b'Pacific/Kwajalein', b'Pacific/Kwajalein'),
                                                                       (b'Asia/Tashkent', b'Asia/Tashkent'),
                                                                       (b'Europe/Rome', b'Europe/Rome'),
                                                                       (b'Asia/Jerusalem', b'Asia/Jerusalem'),
                                                                       (b'Australia/Eucla', b'Australia/Eucla'),
                                                                       (b'Pacific/Chatham', b'Pacific/Chatham'),
                                                                       (b'Australia/Perth', b'Australia/Perth'),
                                                                       (b'Antarctica/Syowa', b'Antarctica/Syowa'),
                                                                       (b'Africa/Djibouti', b'Africa/Djibouti'), (
                                                                       b'America/Indiana/Winamac',
                                                                       b'America/Indiana/Winamac'),
                                                                       (b'Pacific/Honolulu', b'Pacific/Honolulu'),
                                                                       (b'Asia/Baku', b'Asia/Baku'),
                                                                       (b'Africa/Bangui', b'Africa/Bangui'),
                                                                       (b'Africa/Tunis', b'Africa/Tunis'),
                                                                       (b'Europe/Stockholm', b'Europe/Stockholm'),
                                                                       (b'Asia/Seoul', b'Asia/Seoul'),
                                                                       (b'Africa/Lagos', b'Africa/Lagos'), (
                                                                       b'America/Swift_Current',
                                                                       b'America/Swift_Current'), (
                                                                       b'America/Argentina/Cordoba',
                                                                       b'America/Argentina/Cordoba'),
                                                                       (b'Africa/Nouakchott', b'Africa/Nouakchott'), (
                                                                       b'America/Indiana/Vevay',
                                                                       b'America/Indiana/Vevay'),
                                                                       (b'America/Aruba', b'America/Aruba'),
                                                                       (b'Africa/Casablanca', b'Africa/Casablanca'),
                                                                       (b'Asia/Karachi', b'Asia/Karachi'),
                                                                       (b'Africa/Porto-Novo', b'Africa/Porto-Novo'),
                                                                       (b'America/Porto_Velho', b'America/Porto_Velho'),
                                                                       (b'America/North_Dakota/Beulah',
                                                                        b'America/North_Dakota/Beulah'), (
                                                                       b'America/Danmarkshavn',
                                                                       b'America/Danmarkshavn'),
                                                                       (b'Asia/Muscat', b'Asia/Muscat'),
                                                                       (b'America/Belize', b'America/Belize'), (
                                                                       b'America/Port_of_Spain',
                                                                       b'America/Port_of_Spain'),
                                                                       (b'Africa/Nairobi', b'Africa/Nairobi'),
                                                                       (b'Africa/Douala', b'Africa/Douala'),
                                                                       (b'Asia/Baghdad', b'Asia/Baghdad'),
                                                                       (b'Asia/Aqtobe', b'Asia/Aqtobe'),
                                                                       (b'America/Cayman', b'America/Cayman'),
                                                                       (b'Antarctica/Mawson', b'Antarctica/Mawson'),
                                                                       (b'Africa/Bujumbura', b'Africa/Bujumbura'), (
                                                                       b'Pacific/Port_Moresby',
                                                                       b'Pacific/Port_Moresby'),
                                                                       (b'America/Metlakatla', b'America/Metlakatla'),
                                                                       (b'Europe/Athens', b'Europe/Athens'),
                                                                       (b'America/Araguaina', b'America/Araguaina'),
                                                                       (b'Pacific/Gambier', b'Pacific/Gambier'),
                                                                       (b'America/Maceio', b'America/Maceio'),
                                                                       (b'Pacific/Galapagos', b'Pacific/Galapagos'),
                                                                       (b'Asia/Hong_Kong', b'Asia/Hong_Kong'), (
                                                                       b'America/Port-au-Prince',
                                                                       b'America/Port-au-Prince'), (
                                                                       b'America/Argentina/Jujuy',
                                                                       b'America/Argentina/Jujuy'),
                                                                       (b'America/Thule', b'America/Thule'),
                                                                       (b'America/Antigua', b'America/Antigua'),
                                                                       (b'Indian/Maldives', b'Indian/Maldives'),
                                                                       (b'Asia/Anadyr', b'Asia/Anadyr'),
                                                                       (b'Asia/Dili', b'Asia/Dili'),
                                                                       (b'Asia/Hebron', b'Asia/Hebron'),
                                                                       (b'America/Merida', b'America/Merida'),
                                                                       (b'America/Dawson', b'America/Dawson'),
                                                                       (b'Pacific/Wallis', b'Pacific/Wallis'),
                                                                       (b'America/Edmonton', b'America/Edmonton'),
                                                                       (b'Asia/Irkutsk', b'Asia/Irkutsk'),
                                                                       (b'America/Halifax', b'America/Halifax'),
                                                                       (b'America/Juneau', b'America/Juneau'),
                                                                       (b'America/Belem', b'America/Belem'),
                                                                       (b'Europe/Malta', b'Europe/Malta'),
                                                                       (b'America/Adak', b'America/Adak'),
                                                                       (b'Atlantic/Faroe', b'Atlantic/Faroe'), (
                                                                       b'Africa/Dar_es_Salaam',
                                                                       b'Africa/Dar_es_Salaam'),
                                                                       (b'Pacific/Rarotonga', b'Pacific/Rarotonga'), (
                                                                       b'America/Kentucky/Monticello',
                                                                       b'America/Kentucky/Monticello'),
                                                                       (b'Asia/Aqtau', b'Asia/Aqtau'),
                                                                       (b'Australia/Lord_Howe', b'Australia/Lord_Howe'),
                                                                       (b'America/Inuvik', b'America/Inuvik'),
                                                                       (b'Pacific/Auckland', b'Pacific/Auckland'),
                                                                       (b'Asia/Phnom_Penh', b'Asia/Phnom_Penh'),
                                                                       (b'Africa/Gaborone', b'Africa/Gaborone'),
                                                                       (b'America/Los_Angeles', b'America/Los_Angeles'),
                                                                       (b'Pacific/Apia', b'Pacific/Apia'),
                                                                       (b'Asia/Manila', b'Asia/Manila'),
                                                                       (b'Asia/Oral', b'Asia/Oral'),
                                                                       (b'America/Denver', b'America/Denver'),
                                                                       (b'Europe/Oslo', b'Europe/Oslo'),
                                                                       (b'America/Phoenix', b'America/Phoenix'),
                                                                       (b'Asia/Pontianak', b'Asia/Pontianak'),
                                                                       (b'America/Cuiaba', b'America/Cuiaba'),
                                                                       (b'America/Glace_Bay', b'America/Glace_Bay'), (
                                                                       b'Atlantic/South_Georgia',
                                                                       b'Atlantic/South_Georgia'),
                                                                       (b'Asia/Macau', b'Asia/Macau'),
                                                                       (b'Pacific/Chuuk', b'Pacific/Chuuk'),
                                                                       (b'America/Sao_Paulo', b'America/Sao_Paulo'), (
                                                                       b'America/Blanc-Sablon',
                                                                       b'America/Blanc-Sablon'),
                                                                       (b'Asia/Novosibirsk', b'Asia/Novosibirsk'),
                                                                       (b'Asia/Yerevan', b'Asia/Yerevan'),
                                                                       (b'Europe/Luxembourg', b'Europe/Luxembourg'),
                                                                       (b'Asia/Samarkand', b'Asia/Samarkand'),
                                                                       (b'Africa/Blantyre', b'Africa/Blantyre'),
                                                                       (b'America/Manaus', b'America/Manaus'),
                                                                       (b'Australia/Darwin', b'Australia/Darwin'),
                                                                       (b'Atlantic/Bermuda', b'Atlantic/Bermuda'),
                                                                       (b'Europe/Riga', b'Europe/Riga'),
                                                                       (b'Europe/Moscow', b'Europe/Moscow'),
                                                                       (b'America/Rainy_River', b'America/Rainy_River'),
                                                                       (b'Europe/Vilnius', b'Europe/Vilnius'),
                                                                       (b'America/Guadeloupe', b'America/Guadeloupe'),
                                                                       (b'Asia/Ashgabat', b'Asia/Ashgabat'),
                                                                       (b'Asia/Yakutsk', b'Asia/Yakutsk'),
                                                                       (b'Africa/Accra', b'Africa/Accra'),
                                                                       (b'Asia/Vladivostok', b'Asia/Vladivostok'),
                                                                       (b'Asia/Dhaka', b'Asia/Dhaka'),
                                                                       (b'Australia/Brisbane', b'Australia/Brisbane'),
                                                                       (b'Europe/Andorra', b'Europe/Andorra'),
                                                                       (b'Europe/Copenhagen', b'Europe/Copenhagen'),
                                                                       (b'Asia/Brunei', b'Asia/Brunei'),
                                                                       (b'Asia/Kuala_Lumpur', b'Asia/Kuala_Lumpur'),
                                                                       (b'Indian/Kerguelen', b'Indian/Kerguelen'),
                                                                       (b'Asia/Bishkek', b'Asia/Bishkek'),
                                                                       (b'Africa/Bamako', b'Africa/Bamako'),
                                                                       (b'Pacific/Tahiti', b'Pacific/Tahiti'),
                                                                       (b'America/St_Lucia', b'America/St_Lucia'),
                                                                       (b'Africa/Mogadishu', b'Africa/Mogadishu'),
                                                                       (b'Indian/Mahe', b'Indian/Mahe'),
                                                                       (b'Pacific/Kosrae', b'Pacific/Kosrae'),
                                                                       (b'Asia/Kuching', b'Asia/Kuching'),
                                                                       (b'Africa/Maputo', b'Africa/Maputo'),
                                                                       (b'America/Lima', b'America/Lima'), (
                                                                       b'America/Argentina/La_Rioja',
                                                                       b'America/Argentina/La_Rioja'),
                                                                       (b'Africa/Sao_Tome', b'Africa/Sao_Tome'),
                                                                       (b'Europe/Vienna', b'Europe/Vienna'),
                                                                       (b'America/Montevideo', b'America/Montevideo'),
                                                                       (b'America/Santarem', b'America/Santarem'),
                                                                       (b'Asia/Damascus', b'Asia/Damascus'),
                                                                       (b'Europe/Brussels', b'Europe/Brussels'),
                                                                       (b'Europe/Amsterdam', b'Europe/Amsterdam'), (
                                                                       b'America/Cambridge_Bay',
                                                                       b'America/Cambridge_Bay'),
                                                                       (b'America/Eirunepe', b'America/Eirunepe'), (
                                                                       b'America/Argentina/Mendoza',
                                                                       b'America/Argentina/Mendoza'),
                                                                       (b'America/Bogota', b'America/Bogota'),
                                                                       (b'Pacific/Fiji', b'Pacific/Fiji'), (
                                                                       b'America/Campo_Grande',
                                                                       b'America/Campo_Grande'),
                                                                       (b'Africa/Kinshasa', b'Africa/Kinshasa'),
                                                                       (b'Asia/Tbilisi', b'Asia/Tbilisi'),
                                                                       (b'Europe/Zaporozhye', b'Europe/Zaporozhye'), (
                                                                       b'America/Indiana/Marengo',
                                                                       b'America/Indiana/Marengo'),
                                                                       (b'America/El_Salvador', b'America/El_Salvador'),
                                                                       (b'Africa/Brazzaville', b'Africa/Brazzaville'),
                                                                       (b'America/Montreal', b'America/Montreal'),
                                                                       (b'Indian/Mayotte', b'Indian/Mayotte'),
                                                                       (b'Indian/Mauritius', b'Indian/Mauritius'),
                                                                       (b'Asia/Kathmandu', b'Asia/Kathmandu'),
                                                                       (b'Asia/Jakarta', b'Asia/Jakarta'),
                                                                       (b'Pacific/Funafuti', b'Pacific/Funafuti'),
                                                                       (b'Asia/Magadan', b'Asia/Magadan'),
                                                                       (b'America/Hermosillo', b'America/Hermosillo'),
                                                                       (b'Europe/Dublin', b'Europe/Dublin'),
                                                                       (b'Pacific/Pago_Pago', b'Pacific/Pago_Pago'),
                                                                       (b'Asia/Vientiane', b'Asia/Vientiane'),
                                                                       (b'Australia/Melbourne', b'Australia/Melbourne'),
                                                                       (b'Antarctica/Casey', b'Antarctica/Casey'),
                                                                       (b'Africa/Abidjan', b'Africa/Abidjan'), (
                                                                       b'Antarctica/Macquarie',
                                                                       b'Antarctica/Macquarie'),
                                                                       (b'Europe/Budapest', b'Europe/Budapest'),
                                                                       (b'Pacific/Efate', b'Pacific/Efate'),
                                                                       (b'America/Managua', b'America/Managua'),
                                                                       (b'America/Boa_Vista', b'America/Boa_Vista'), (
                                                                       b'America/Indiana/Tell_City',
                                                                       b'America/Indiana/Tell_City'),
                                                                       (b'America/Toronto', b'America/Toronto'),
                                                                       (b'Pacific/Majuro', b'Pacific/Majuro'),
                                                                       (b'America/Mexico_City', b'America/Mexico_City'),
                                                                       (b'Pacific/Tarawa', b'Pacific/Tarawa'),
                                                                       (b'America/Whitehorse', b'America/Whitehorse'),
                                                                       (b'America/Yakutat', b'America/Yakutat'),
                                                                       (b'Africa/Lome', b'Africa/Lome'),
                                                                       (b'Pacific/Pitcairn', b'Pacific/Pitcairn'),
                                                                       (b'Africa/Kigali', b'Africa/Kigali'),
                                                                       (b'Asia/Riyadh', b'Asia/Riyadh'),
                                                                       (b'America/Grand_Turk', b'America/Grand_Turk'),
                                                                       (b'Europe/Tallinn', b'Europe/Tallinn'), (
                                                                       b'America/Bahia_Banderas',
                                                                       b'America/Bahia_Banderas'),
                                                                       (b'America/Nome', b'America/Nome'),
                                                                       (b'Pacific/Pohnpei', b'Pacific/Pohnpei'),
                                                                       (b'Africa/Ouagadougou', b'Africa/Ouagadougou'),
                                                                       (b'Asia/Ho_Chi_Minh', b'Asia/Ho_Chi_Minh'),
                                                                       (b'Asia/Thimphu', b'Asia/Thimphu'),
                                                                       (b'Asia/Krasnoyarsk', b'Asia/Krasnoyarsk'),
                                                                       (b'Africa/Bissau', b'Africa/Bissau'),
                                                                       (b'Atlantic/Canary', b'Atlantic/Canary'),
                                                                       (b'Asia/Beirut', b'Asia/Beirut'),
                                                                       (b'Asia/Kabul', b'Asia/Kabul'),
                                                                       (b'America/Santiago', b'America/Santiago'),
                                                                       (b'Pacific/Marquesas', b'Pacific/Marquesas'),
                                                                       (b'Asia/Kuwait', b'Asia/Kuwait'),
                                                                       (b'Africa/Windhoek', b'Africa/Windhoek'),
                                                                       (b'Pacific/Enderbury', b'Pacific/Enderbury'),
                                                                       (b'Asia/Omsk', b'Asia/Omsk'),
                                                                       (b'Pacific/Niue', b'Pacific/Niue'), (
                                                                       b'America/Argentina/Ushuaia',
                                                                       b'America/Argentina/Ushuaia'),
                                                                       (b'Asia/Singapore', b'Asia/Singapore'),
                                                                       (b'Europe/Tirane', b'Europe/Tirane'),
                                                                       (b'America/Detroit', b'America/Detroit'),
                                                                       (b'Asia/Novokuznetsk', b'Asia/Novokuznetsk'),
                                                                       (b'Indian/Cocos', b'Indian/Cocos'),
                                                                       (b'Africa/Freetown', b'Africa/Freetown'),
                                                                       (b'America/Havana', b'America/Havana'),
                                                                       (b'Pacific/Fakaofo', b'Pacific/Fakaofo'), (
                                                                       b'America/North_Dakota/Center',
                                                                       b'America/North_Dakota/Center'),
                                                                       (b'Africa/Banjul', b'Africa/Banjul'),
                                                                       (b'America/Rio_Branco', b'America/Rio_Branco'), (
                                                                       b'America/Argentina/Tucuman',
                                                                       b'America/Argentina/Tucuman'),
                                                                       (b'America/Creston', b'America/Creston'),
                                                                       (b'Europe/Prague', b'Europe/Prague'),
                                                                       (b'Europe/Gibraltar', b'Europe/Gibraltar'),
                                                                       (b'Antarctica/Vostok', b'Antarctica/Vostok'),
                                                                       (b'Pacific/Kiritimati', b'Pacific/Kiritimati'),
                                                                       (b'Atlantic/Reykjavik', b'Atlantic/Reykjavik'),
                                                                       (b'Atlantic/Stanley', b'Atlantic/Stanley'),
                                                                       (b'Africa/Khartoum', b'Africa/Khartoum'),
                                                                       (b'America/Yellowknife', b'America/Yellowknife'),
                                                                       (b'Europe/Warsaw', b'Europe/Warsaw'),
                                                                       (b'America/St_Vincent', b'America/St_Vincent'),
                                                                       (b'Indian/Chagos', b'Indian/Chagos'),
                                                                       (b'Asia/Ulaanbaatar', b'Asia/Ulaanbaatar'),
                                                                       (b'Asia/Makassar', b'Asia/Makassar'),
                                                                       (b'Africa/Mbabane', b'Africa/Mbabane'),
                                                                       (b'Pacific/Nauru', b'Pacific/Nauru'), (
                                                                       b'Australia/Broken_Hill',
                                                                       b'Australia/Broken_Hill'),
                                                                       (b'Africa/Lubumbashi', b'Africa/Lubumbashi'),
                                                                       (b'Australia/Sydney', b'Australia/Sydney'),
                                                                       (b'Antarctica/Rothera', b'Antarctica/Rothera'),
                                                                       (b'Europe/Paris', b'Europe/Paris'),
                                                                       (b'Africa/Addis_Ababa', b'Africa/Addis_Ababa'),
                                                                       (b'America/Recife', b'America/Recife'),
                                                                       (b'Europe/Sofia', b'Europe/Sofia'),
                                                                       (b'America/Moncton', b'America/Moncton'),
                                                                       (b'Australia/Currie', b'Australia/Currie'),
                                                                       (b'Europe/Monaco', b'Europe/Monaco'),
                                                                       (b'Pacific/Midway', b'Pacific/Midway'),
                                                                       (b'Pacific/Johnston', b'Pacific/Johnston'),
                                                                       (b'America/Boise', b'America/Boise'),
                                                                       (b'America/Ojinaga', b'America/Ojinaga'),
                                                                       (b'Australia/Lindeman', b'Australia/Lindeman'), (
                                                                       b'America/Argentina/Salta',
                                                                       b'America/Argentina/Salta'),
                                                                       (b'Asia/Taipei', b'Asia/Taipei'),
                                                                       (b'Pacific/Easter', b'Pacific/Easter'),
                                                                       (b'Africa/Maseru', b'Africa/Maseru'),
                                                                       (b'Europe/Kiev', b'Europe/Kiev'),
                                                                       (b'Europe/Vaduz', b'Europe/Vaduz'), (
                                                                       b'America/Argentina/Buenos_Aires',
                                                                       b'America/Argentina/Buenos_Aires'),
                                                                       (b'America/Noronha', b'America/Noronha'), (
                                                                       b'America/Argentina/San_Luis',
                                                                       b'America/Argentina/San_Luis'),
                                                                       (b'Pacific/Guam', b'Pacific/Guam'),
                                                                       (b'Asia/Hovd', b'Asia/Hovd'), (
                                                                       b'America/Argentina/Rio_Gallegos',
                                                                       b'America/Argentina/Rio_Gallegos'),
                                                                       (b'America/Nipigon', b'America/Nipigon'), (
                                                                       b'Antarctica/DumontDUrville',
                                                                       b'Antarctica/DumontDUrville'),
                                                                       (b'America/Panama', b'America/Panama'),
                                                                       (b'America/Costa_Rica', b'America/Costa_Rica'),
                                                                       (b'America/Matamoros', b'America/Matamoros'),
                                                                       (b'America/Resolute', b'America/Resolute'),
                                                                       (b'Africa/Conakry', b'Africa/Conakry'),
                                                                       (b'America/Curacao', b'America/Curacao'),
                                                                       (b'Asia/Kamchatka', b'Asia/Kamchatka'),
                                                                       (b'Asia/Pyongyang', b'Asia/Pyongyang'),
                                                                       (b'Asia/Bangkok', b'Asia/Bangkok'),
                                                                       (b'Africa/Monrovia', b'Africa/Monrovia'),
                                                                       (b'Europe/Uzhgorod', b'Europe/Uzhgorod'),
                                                                       (b'America/Winnipeg', b'America/Winnipeg'),
                                                                       (b'America/St_Johns', b'America/St_Johns'),
                                                                       (b'America/Puerto_Rico', b'America/Puerto_Rico'),
                                                                       (b'Asia/Dubai', b'Asia/Dubai'),
                                                                       (b'Africa/Niamey', b'Africa/Niamey'),
                                                                       (b'Antarctica/Palmer', b'Antarctica/Palmer'),
                                                                       (b'Africa/Luanda', b'Africa/Luanda'),
                                                                       (b'Indian/Christmas', b'Indian/Christmas'),
                                                                       (b'Europe/London', b'Europe/London'),
                                                                       (b'America/Mazatlan', b'America/Mazatlan'),
                                                                       (b'Europe/Madrid', b'Europe/Madrid'),
                                                                       (b'Pacific/Saipan', b'Pacific/Saipan'),
                                                                       (b'America/Thunder_Bay', b'America/Thunder_Bay'),
                                                                       (b'America/Scoresbysund',
                                                                        b'America/Scoresbysund')]),
        ),
    ]
