# -*- coding: utf-8 -*-
# Generated by Django 1.9.4 on 2016-03-21 13:36
from __future__ import unicode_literals

import django_enumfield.db.fields
from django.db import migrations

import apps.incidents.models


class Migration(migrations.Migration):
    dependencies = [
        ('incidents', '0015_auto_20160115_1629'),
    ]

    operations = [
        migrations.AlterField(
            model_name='incidenttemplateexceptions',
            name='type',
            field=django_enumfield.db.fields.EnumField(default=0, enum=apps.incidents.models.Type),
        ),
    ]
